---
- name: Install TightVNC server on Amazon Linux EC2
  hosts: bastion
  become: true
  vars:
    vnc_password: {{ lookup('env','TF_VAR_rdx_password') }}
  tasks:
    - name: Update yum cache
      yum:
        update_cache: true
    - name: Install required packages
      yum:
        name:
          - tigervnc-server
          - xorg-x11-fonts-Type1
        state: present
    - name: Configure VNC password
      shell: |
        mkdir -p ~/.vnc
        echo "{{ vnc_password }}" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
    - name: Start VNC server
      shell: |
        vncserver :1 -geometry 1280x800 -depth 24
        echo 'export DISPLAY=:1' >> ~/.bashrc
        echo 'export VNCUSERARGS="-localhost no"' >> ~/.bashrc
- name: Install packages and configure Docker
  hosts: stack
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
    - name: Install packages
      apt:
        name:
          - wget
          - docker.io
          - docker-compose
          - rng-tools
        state: present
    - name: Start RNGD service
      service:
        name: rng-tools
        state: started
    - name: Apply sudo rngd -r /dev/random command
      command: sudo rngd -r /dev/random
    - name: Create Docker group
      group:
        name: docker
        state: present
    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: Reset connection
      meta: reset_connection
