---
- name: Install TightVNC server on Amazon Linux EC2
  hosts: bastion
  become: true
  vars:
    vnc_password: lookup('env', 'TF_VAR_rdx_password')
    tasks:
    - name: Install TightVNC server
      yum:
        name: tightvnc-server
        state: present    
    - name: Set VNC password
      shell: |
        echo "{{ vnc_password }}" | vncpasswd -f > /home/{{ remote_user }}/.vnc/passwd
      register: vnc_password_set
      changed_when: vnc_password_set.stdout != ""
      when: vnc_password is defined    
    - name: Configure TightVNC server
      lineinfile:
        path: /usr/lib/systemd/system/vncserver@.service
        line: "ExecStart=/usr/bin/tightvncserver -depth 24 -geometry 1280x800 -SecurityTypes=VncAuth :%i"
        state: present      
    - name: Start and enable TightVNC server
      systemd:
        name: vncserver@:1.service
        state: started
        enabled: true
- name: Install packages and configure Docker
  hosts: stack
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
    - name: Install packages
      apt:
        name:
          - wget
          - docker.io
          - docker-compose
          - rng-tools
        state: present
    - name: Start RNGD service
      service:
        name: rng-tools
        state: started
    - name: Apply sudo rngd -r /dev/random command
      command: sudo rngd -r /dev/random
    - name: Create Docker group
      group:
        name: docker
        state: present
    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: Reset connection
      meta: reset_connection
