---
- name: Configure Bastion
  hosts: bastion
  become: true
  tasks:
    - name: Set user password
      user:
        name: "{{ username }}"
        password: "{{ lookup('env', 'TF_VAR_rdx_password') }}"
        update_password: always
- name: Install packages and configure Docker
  hosts: all
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
    - name: Install packages
      apt:
        name:
          - wget
          - docker.io
          - docker-compose
          - rng-tools
        state: present
    - name: Start RNGD service
      service:
        name: rng-tools
        state: started
    - name: Apply sudo rngd -r /dev/random command
      command: sudo rngd -r /dev/random
    - name: Create Docker group
      group:
        name: docker
        state: present
    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: Reset connection
      meta: reset_connection
