name: "Deploy Infrastructure"
on:
  push:
    branches:
      - main
      - dev
permissions:
      id-token: write
      contents: read
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_rdx_public_key: ${{ secrets.RDX_PUBLIC_KEY }}
  TF_VAR_rdx_private_key: ${{ secrets.RDX_PRIVATE_KEY }}
  TF_VAR_token_github: ${{ secrets.TOKEN_GITHUB }}
jobs:
  check_changes:
    name: Check Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          terraform:
            - 'terraform/**'
  infra_setup:
    name: Run Terraform
    needs: check_changes
    if: ${{ needs.check_changes.outputs.terraform == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      - name: Check Formatting
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Initialize Terraform
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
      - name: Validate Terraform Code
        id: validate
        run: terraform validate -no-color
      - name: Run Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
      - name: Check Terraform Plan
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Apply Terraform
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name == 'push') }}
        run: terraform apply -auto-approve -input=false